-- ============================================================
-- 휴가 유형 공통코드 (CL_CODE = 221)
-- ANNUAL_LEAVE_HISTORY.ANN_TYPE_CD 가 참조하는 휴가 유형 코드.
-- 공통코드 관리 화면(/admin/common-codes)에서도 동일하게 관리/수정 가능.
-- 멱등(NOT EXISTS) 처리되어 여러 번 실행해도 안전함.
-- ============================================================

-- 분류 등록
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '221','휴가 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='221');

-- 코드 등록 (ANN_TYPE_CD = CHAR(2))
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','221','연차','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','221','반차','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','221','병가','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','221','공가','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '05','221','경조사','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='05' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '06','221','출산휴가','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='06' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '07','221','육아휴직','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='07' AND TRIM(CL_CODE)='221');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '08','221','특별휴가','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='08' AND TRIM(CL_CODE)='221');

COMMIT;
