-- DEPT_CD = 'D300' (강사팀) 소속 직원 전원을 INSTRUCTOR 테이블에 일괄 INSERT
-- INSTRUCTOR 테이블이 비어있으므로 NOT EXISTS 조건 없이 단순 INSERT
INSERT INTO INSTRUCTOR (INSTR_USER_ID)
SELECT USER_ID
FROM EMPLOYEE_INFO
WHERE DEPT_CD = 'D300';

COMMIT;

-- 결과 확인
SELECT i.INSTR_USER_ID, m.USER_NAME
FROM INSTRUCTOR i
JOIN MEMBER m ON i.INSTR_USER_ID = m.USER_ID
ORDER BY i.INSTR_USER_ID;
