-- ============================================================
-- 퇴원 방어 및 유지 관리 (manager/retention.html) 공통코드
--  · 226 출결 유형 : STUDENT_ATTENDANCE.ATND_TYPE_CD
--  · 227 퇴원방어 결과 : RETENTION_PROCESS.RTNP_RSLT_CD
--  · 퇴원 사유는 기존 203(학생 퇴소 사유) 사용
-- ============================================================

-- ── 226. 출결 유형 ──────────────────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '226','출결 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='226');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','226','출석','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='226');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','226','결석','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='226');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','226','지각','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='226');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','226','조퇴','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='226');

-- ── 227. 퇴원방어 결과 ──────────────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '227','퇴원방어 결과','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='227');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','227','진행중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='227');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','227','유지','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='227');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','227','퇴원','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='227');

COMMIT;
