package kr.or.ddit.finalProject.mapper.subject;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import kr.or.ddit.finalProject.dto.subject.SubjectClassificationDto;
import kr.or.ddit.finalProject.dto.subject.SubjectDto;

@Mapper
public interface SubjectMapper {

    // ── 대분류(SUBJECT_CLASSIFICATION) ─────────────────────────────

    /** USE_YN = 'Y'인 대분류 목록을 등록일 오름차순으로 반환한다. */
    List<SubjectClassificationDto> selectClassificationList();

    /** subjClId로 대분류 단건을 조회한다. USE_YN 무관. */
    SubjectClassificationDto selectClassificationById(@Param("subjClId") Long subjClId);

    /** 대분류를 INSERT한다. GENERATED BY DEFAULT AS IDENTITY로 PK가 채워진다. */
    int insertClassification(SubjectClassificationDto dto);

    /** 대분류 이름·최종수정자를 UPDATE한다. */
    int updateClassification(SubjectClassificationDto dto);

    /** 대분류를 논리 삭제한다 (USE_YN = 'N'). */
    int deleteClassificationLogically(@Param("subjClId") Long subjClId,
            @Param("lastMdfrId") String lastMdfrId);

    /** 대분류에 속한 USE_YN = 'Y' 과목 수를 반환한다. 삭제 가드에 사용. */
    int countSubjectsByClassification(@Param("subjClId") Long subjClId);

    // ── 과목(SUBJECT) ──────────────────────────────────────────────

    /** 특정 대분류의 USE_YN = 'Y' 과목 목록을 등록일 오름차순으로 반환한다. */
    List<SubjectDto> selectSubjectList(@Param("subjClId") Long subjClId);

    /** subjId + subjClId로 과목 단건을 조회한다. USE_YN 무관. */
    SubjectDto selectSubjectById(@Param("subjId") Long subjId,
            @Param("subjClId") Long subjClId);

    /** 과목을 INSERT한다. GENERATED BY DEFAULT AS IDENTITY로 PK가 채워진다. */
    int insertSubject(SubjectDto dto);

    /** 과목 이름·설명·최종수정자를 UPDATE한다. */
    int updateSubject(SubjectDto dto);

    /** 과목을 논리 삭제한다 (USE_YN = 'N'). */
    int deleteSubjectLogically(@Param("subjId") Long subjId,
            @Param("subjClId") Long subjClId,
            @Param("lastMdfrId") String lastMdfrId);

    /** 해당 과목을 참조하는 강좌 수를 반환한다. 삭제 가드에 사용. */
    int countCoursesBySubject(@Param("subjId") Long subjId);
}
