spring.application.name=rest
server.port=8081


spring.config.import=classpath:common-config.properties

# Redis
spring.data.redis.host=${redis_host}
spring.data.redis.port=6379
spring.data.redis.password=${redis_password}

# File Server
file.server.base-url=${file_server_url}