-- =====================================================================
-- 전체 테이블 DROP 스크립트 (Oracle)
-- 실행 후 create_all_tables.sql + create_member_table.sql 로 재생성 가능
-- CASCADE CONSTRAINTS : 참조 FK 도 함께 제거
-- PURGE              : 휴지통(Recycle Bin) 건너뜀
-- =====================================================================

-- FK 참조 대상 테이블 (나중에 DROP)
DROP TABLE PARENT_JOIN_LINK        CASCADE CONSTRAINTS PURGE;
DROP TABLE PAY_HIST                CASCADE CONSTRAINTS PURGE;
DROP TABLE CMMT_ATCH_FILE_DTL      CASCADE CONSTRAINTS PURGE;
DROP TABLE PAY_CNCL_HIST           CASCADE CONSTRAINTS PURGE;
DROP TABLE APPROVAL_TEMPLATE       CASCADE CONSTRAINTS PURGE;
DROP TABLE TEXTBOOK_INVENTORY      CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT_BLACK_LIST      CASCADE CONSTRAINTS PURGE;
DROP TABLE APPROVAL_LINE           CASCADE CONSTRAINTS PURGE;
DROP TABLE MESSAGE_ROOM            CASCADE CONSTRAINTS PURGE;
DROP TABLE EXAM                    CASCADE CONSTRAINTS PURGE;
DROP TABLE COM_CL                  CASCADE CONSTRAINTS PURGE;
DROP TABLE QNA                     CASCADE CONSTRAINTS PURGE;
DROP TABLE POST_RECEIVER           CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT                 CASCADE CONSTRAINTS PURGE;
DROP TABLE COURSE_CONTENT          CASCADE CONSTRAINTS PURGE;
DROP TABLE COURSE_PLAN             CASCADE CONSTRAINTS PURGE;
DROP TABLE LECTURE                 CASCADE CONSTRAINTS PURGE;
DROP TABLE COM_CD                  CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT_ATTENDANCE      CASCADE CONSTRAINTS PURGE;
DROP TABLE INSTRUCTOR_DATA_ROOM    CASCADE CONSTRAINTS PURGE;
DROP TABLE SUBJECT                 CASCADE CONSTRAINTS PURGE;
DROP TABLE POPUP                   CASCADE CONSTRAINTS PURGE;
DROP TABLE STUDENT_BLACK_LIST_HISTORY CASCADE CONSTRAINTS PURGE;
DROP TABLE APPROVAL_MASTER         CASCADE CONSTRAINTS PURGE;
DROP TABLE ANNUAL_LEAVE_HISTORY    CASCADE CONSTRAINTS PURGE;
DROP TABLE POST_MASTER             CASCADE CONSTRAINTS PURGE;
DROP TABLE MESSAGE_CONTENT         CASCADE CONSTRAINTS PURGE;
DROP TABLE QUESTION_LIST           CASCADE CONSTRAINTS PURGE;
DROP TABLE FAQ                     CASCADE CONSTRAINTS PURGE;
DROP TABLE INSTRUCTOR_BOARD_COMMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE ANSWER_SUBMIT           CASCADE CONSTRAINTS PURGE;
DROP TABLE ASSIGNMENT_BOARD        CASCADE CONSTRAINTS PURGE;
DROP TABLE SUBJECT_CLASSIFICATION  CASCADE CONSTRAINTS PURGE;
DROP TABLE CMMT_ATCH_FILE_CL       CASCADE CONSTRAINTS PURGE;
DROP TABLE BOARD_COMMENT           CASCADE CONSTRAINTS PURGE;
DROP TABLE CLASSROOM               CASCADE CONSTRAINTS PURGE;
DROP TABLE INSTRUCTOR_BOARD        CASCADE CONSTRAINTS PURGE;
DROP TABLE ASSIGNMENT_SUBMIT       CASCADE CONSTRAINTS PURGE;
DROP TABLE INSTRUCTOR              CASCADE CONSTRAINTS PURGE;
DROP TABLE TEXTBOOK                CASCADE CONSTRAINTS PURGE;
DROP TABLE POST_SENDER             CASCADE CONSTRAINTS PURGE;
DROP TABLE EXAM_TAKER              CASCADE CONSTRAINTS PURGE;
DROP TABLE COURSE_SATISFACTION     CASCADE CONSTRAINTS PURGE;
DROP TABLE DATA_ROOM               CASCADE CONSTRAINTS PURGE;
DROP TABLE CARD_PAY_HIST           CASCADE CONSTRAINTS PURGE;
DROP TABLE EMPLOYEE_INFO           CASCADE CONSTRAINTS PURGE;
DROP TABLE MESSAGE_ROOM_PARTICIPANT CASCADE CONSTRAINTS PURGE;
DROP TABLE JOB_GRADE               CASCADE CONSTRAINTS PURGE;
DROP TABLE EXAM_QUESTION           CASCADE CONSTRAINTS PURGE;
DROP TABLE QUESTION_PASSAGE        CASCADE CONSTRAINTS PURGE;
DROP TABLE EMP_ATTENDANCE          CASCADE CONSTRAINTS PURGE;
DROP TABLE INSTRUCTOR_QNA          CASCADE CONSTRAINTS PURGE;
DROP TABLE BOARD                   CASCADE CONSTRAINTS PURGE;
DROP TABLE COURSE                  CASCADE CONSTRAINTS PURGE;
DROP TABLE TEXTBOOK_HISTORY        CASCADE CONSTRAINTS PURGE;
DROP TABLE DEPARTMENT              CASCADE CONSTRAINTS PURGE;

-- MEMBER 관련 (create_member_table.sql 로 만든 테이블)
DROP TABLE MEMBER_ROLE_MAPPING     CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER_ROLE             CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER                  CASCADE CONSTRAINTS PURGE;
