spring.application.name=final

# Oracle DB 연결 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@${db_host}:1521:xe
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

# MyBatis 설정
# XML 매퍼 위치 (resources 폴더 아래 mapper 폴더 생성 필요)
mybatis.mapper-locations=classpath:mapper/**/*.xml

# DTO가 모여있는 패키지 경로 (XML에서 이름만 쓰고 싶을 때 사용)
mybatis.type-aliases-package=kr.or.ddit.final.dto

# 카멜케이스 자동 변환 (DB의 USER_ID를 Java의 userId로 매핑)
mybatis.configuration.map-underscore-to-camel-case=true

# 서버 포트 설정
server.port=8081



# Cloudinary 설정
cloudinary.cloud-name=dczqmsune
cloudinary.api-key=129132361988447
cloudinary.api-secret=nPYfHveu7oXpGAWgyGDc1HRaac4