spring.application.name=final

# Oracle DB 연결 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 아래의 변수들은 환경에 맞게 설정해야 함
# .env 파일에 db_host, db_username, db_password 변수를 정의하고 사용
spring.datasource.url=jdbc:oracle:thin:@${db_host}:1521:xe
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}


# MyBatis 설정
# XML 매퍼 위치 (resources 폴더 아래 mapper 폴더 생성 필요)
mybatis.mapper-locations=classpath*:mapper/**/*.xml

# DTO가 모여있는 패키지 경로 (XML에서 이름만 쓰고 싶을 때 사용)
mybatis.type-aliases-package=kr.or.ddit.finalProject.dto

# 카멜케이스 자동 변환 (DB의 USER_ID를 Java의 userId로 매핑)
mybatis.configuration.map-underscore-to-camel-case=true



# Cloudinary 설정
cloudinary.cloud-name=dczqmsune
cloudinary.api-key=${cloudinary_api_key}
cloudinary.api-secret=${cloudinary_api_secret}

# JWT 설정

jwt.secret=${jwt_secret}

# 1시간 (밀리초 단위)
jwt.accessTokenExpiration=3600000 

# 1일 (밀리초 단위)
jwt.refreshTokenExpiration=86400000 

# JWT 토큰에서 사용할 비밀 키
app.token.secret-key=${jwt_secret}


# Logging 설정
spring.output.ansi.enabled=always
logging.include-application-name=false
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr([%15.15t]){blue} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.exception-conversion-word=%wEx

logging.level.root=INFO
logging.level.kr.or.ddit=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO


# Oracle Email Delivery 설정
spring.mail.host=smtp.email.ap-chuncheon-1.oci.oraclecloud.com
spring.mail.port=587
spring.mail.username=${smtp_username}
spring.mail.password=${smtp_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

email.sender=${email_sender}

kakao.pay.secret.key=${kakao_pay_secret_key}

