-- EXAM_TAKER 테이블에 점수 및 응시일시 컬럼 추가
ALTER TABLE EXAM_TAKER ADD (
    TOT_SCORE  NUMBER(6,2)  NULL,
    SBMT_DT    TIMESTAMP    NULL
);

COMMENT ON COLUMN EXAM_TAKER.TOT_SCORE IS '총점';
COMMENT ON COLUMN EXAM_TAKER.SBMT_DT   IS '응시 제출 일시';
