-- QUESTION_LIST 테이블 AI 문항 생성 기능 대응 변경
-- 기존 더미 데이터 제거 (마이그레이션 없음)
TRUNCATE TABLE EXAM_QUESTION;
TRUNCATE TABLE QUESTION_LIST;

-- 과목 소분류 코드 제거 (COM_CD 참조였으나 실제 SUBJECT 테이블과 무관한 죽은 컬럼)
ALTER TABLE QUESTION_LIST DROP COLUMN SUBJ_DTCL_CD;

-- 수정일 컬럼명 변경 (MDFCN_DT로 변경하여 의미 명확화)
ALTER TABLE QUESTION_LIST RENAME COLUMN FIELD5 TO MDFCN_DT;

-- 문항 유형 코드: CHAR(2) → VARCHAR2(20) (QuestionType enum 값 저장: MULTIPLE_CHOICE / SHORT_ANSWER / ESSAY)
ALTER TABLE QUESTION_LIST MODIFY QSTN_TYPE_CD VARCHAR2(20);

-- 과목 FK 추가 (SUBJECT 테이블 소분류와 직접 연결)
ALTER TABLE QUESTION_LIST ADD SUBJ_ID NUMBER(20);
ALTER TABLE QUESTION_LIST ADD CONSTRAINT FK_QSTN_SUBJ
    FOREIGN KEY (SUBJ_ID) REFERENCES SUBJECT(SUBJ_ID);

-- 난이도 추가 (Difficulty enum: EASY / MEDIUM / HARD)
ALTER TABLE QUESTION_LIST ADD DIFF_CD VARCHAR2(10);

-- AI 생성 여부 추가
ALTER TABLE QUESTION_LIST ADD AI_GEN_YN CHAR(1) DEFAULT 'N' NOT NULL;

-- 코멘트 갱신
COMMENT ON COLUMN QUESTION_LIST.QSTN_TYPE_CD IS '문항 유형 (MULTIPLE_CHOICE=객관식 / SHORT_ANSWER=단답형 / ESSAY=서술형)';
COMMENT ON COLUMN QUESTION_LIST.CORR_ANSW_CN IS '정답 (객관식=선지 레이블 예:A / 단답형=정답 텍스트 / 서술형=채점 기준)';
COMMENT ON COLUMN QUESTION_LIST.SUBJ_ID       IS '과목 ID (SUBJECT.SUBJ_ID FK)';
COMMENT ON COLUMN QUESTION_LIST.DIFF_CD       IS '난이도 (EASY=쉬움 / MEDIUM=보통 / HARD=어려움)';
COMMENT ON COLUMN QUESTION_LIST.AI_GEN_YN     IS 'AI 생성 여부 (Y=Gemini 생성 / N=수동 작성)';

COMMIT;
