-- ASSIGNMENT_SUBMIT 테이블에 채점자 ID 컬럼 추가
ALTER TABLE ASSIGNMENT_SUBMIT ADD (
    GRDD_USER_ID VARCHAR2(50) NULL
);

COMMENT ON COLUMN ASSIGNMENT_SUBMIT.GRDD_USER_ID IS '채점자 사용자 ID (MEMBER.USER_ID)';

COMMIT;
