-- ================================================================
-- 공통코드 초기 데이터 INSERT (200번대 - staff/principal/manager)
-- 100번대는 게시판 모듈 팀원이 사용 중
-- 중복 방지 (WHERE NOT EXISTS) 적용 - 재실행 안전
-- ================================================================

-- ── 200. 재직 상태 (employees.html, org.html) ────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '200','재직 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='200');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','200','재직 중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='200');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','200','휴직 중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='200');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','200','퇴사','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='200');

-- ── 201. 고용 형태 (employees.html) ─────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '201','고용 형태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='201');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','201','정규직','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='201');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','201','계약직','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='201');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','201','파트타임','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='201');

-- ── 202. 직원 퇴사 사유 (employees.html) ────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '202','직원 퇴사 사유','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='202');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','202','개인 사정','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='202');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','202','계약 만료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='202');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','202','권고사직','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='202');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','202','기타','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='202');

-- ── 203. 학생 퇴소 사유 (students.html) ─────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '203','학생 퇴소 사유','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='203');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','203','본인 요청','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='203');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','203','장기 미접속','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='203');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','203','운영 정책 위반','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='203');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','203','기타','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='203');

-- ── 204. 블랙리스트 등급 (blacklist.html) ───────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '204','블랙리스트 등급','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='204');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','204','고위험','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='204');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','204','관찰 중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='204');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','204','해제 완료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='204');

-- ── 205. 블랙리스트 유형 (blacklist.html) ───────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '205','블랙리스트 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='205');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','205','폭력/괴롭힘','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='205');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','205','수납 불이행','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='205');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','205','수업 태도','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='205');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','205','기타','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='205');

-- ── 206. 재고 카테고리 (logistics.html) ─────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '206','재고 카테고리','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='206');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','206','수학','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='206');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','206','영어','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='206');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','206','과학','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='206');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','206','소모품','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='206');

-- ── 207. 재고 상태 (logistics.html) ─────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '207','재고 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='207');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','207','재고 부족','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='207');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','207','정상','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='207');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','207','충분','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='207');

-- ── 208. 교재 배부 상태 (logistics.html) ────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '208','교재 배부 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='208');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','208','지급 완료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='208');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','208','미수령','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='208');

-- ── 209. 결재 유형 (approval_request.html) ──────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '209','결재 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='209');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','209','인사','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='209');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','209','예산/지출','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='209');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','209','학사 운영','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='209');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','209','시설/환경','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='209');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '05','209','기타','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='05' AND TRIM(CL_CODE)='209');

-- ── 210. 결재 긴급도 (approval_request.html) ────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '210','결재 긴급도','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='210');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','210','일반','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='210');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','210','긴급','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='210');

-- ── 211. 상담 유형 (consultation.html) ──────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '211','상담 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='211');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','211','대면','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='211');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','211','전화','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='211');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','211','문자','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='211');

-- ── 212. 상담 상태 (consultation.html) ──────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '212','상담 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='212');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','212','예정','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='212');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','212','완료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='212');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','212','후속 조치','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='212');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','212','취소','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='212');

-- ── 213. 과목 (monitoring.html) ─────────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '213','과목','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='213');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','213','수학','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='213');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','213','영어','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='213');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','213','국어','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='213');

-- ── 214. 수업 상태 (monitoring.html) ────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '214','수업 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='214');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','214','진행 중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='214');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','214','준비 중','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='214');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','214','종료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='214');

-- ── 215. 재무 거래 유형 (finance.html) ──────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '215','재무 거래 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='215');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','215','수입','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='215');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','215','지출','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='215');

-- ── 216. 재무 항목 (finance.html) ───────────────────────────────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '216','재무 항목','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='216');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','216','원비','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='216');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','216','교재비','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='216');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','216','강사 급여','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='216');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','216','임대료','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='216');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '05','216','기타','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='05' AND TRIM(CL_CODE)='216');

-- ── 217. 사용자 활동 유형 (principal_system_monitoring.html) ────
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '217','사용자 활동 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='217');

INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '01','217','강의 재생','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='01' AND TRIM(CL_CODE)='217');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '02','217','과제 제출','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='02' AND TRIM(CL_CODE)='217');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '03','217','게시글 조회','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='03' AND TRIM(CL_CODE)='217');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '04','217','댓글 작성','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='04' AND TRIM(CL_CODE)='217');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '05','217','자료 다운로드','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='05' AND TRIM(CL_CODE)='217');

-- ── 218. 연도 (employees.html, students.html 연도 필터)
--        CONNECT BY LEVEL 로 2000년 ~ 현재연도 자동 생성
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '218','연도','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='218');

INSERT INTO COM_CD (COM_CD, CL_CODE, COM_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT yr, '218', yr || '년', 'Y', 'SYSTEM', SYSTIMESTAMP
FROM (
    SELECT TO_CHAR(1999 + LEVEL) AS yr
    FROM DUAL
    CONNECT BY 1999 + LEVEL <= EXTRACT(YEAR FROM SYSDATE)
)
WHERE NOT EXISTS (
    SELECT 1 FROM COM_CD C2
    WHERE TRIM(C2.COM_CD) = yr AND TRIM(C2.CL_CODE) = '218'
);

-- ── 219. 학생 상태 (students.html hr-status-filter)
--        기존 value="Y","N" 유지
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '219','학생 상태','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='219');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT 'Y','219','정상','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='Y' AND TRIM(CL_CODE)='219');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT 'N','219','탈퇴','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='N' AND TRIM(CL_CODE)='219');

-- ── 220. 학생 유형 (students.html hr-type-filter)
--        ROLE_STUDENT(12자)가 CHAR(10) 초과 → '일반'/'오프라인'을 COM_CD로 사용
--        JS에서 '일반'→'ROLE_USER', '오프라인'→'ROLE_STUDENT' 매핑 후 백엔드 전달
INSERT INTO COM_CL (CL_CODE, CL_CD_NM, USE_YN, RGTR_ID, REG_DT)
SELECT '220','학생 유형','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CL WHERE TRIM(CL_CODE)='220');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '일반','220','일반','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='일반' AND TRIM(CL_CODE)='220');
INSERT INTO COM_CD (COM_CD,CL_CODE,COM_CD_NM,USE_YN,RGTR_ID,REG_DT)
SELECT '오프라인','220','오프라인','Y','SYSTEM',SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CD WHERE TRIM(COM_CD)='오프라인' AND TRIM(CL_CODE)='220');


COMMIT;
