CREATE TABLE LECTURE_PROGRESS (
    USER_ID         VARCHAR2(20)  NOT NULL,
    COURSE_SN       NUMBER(20)    NOT NULL, -- 부모의 복합키 조각인 COURSE_SN 추가
    LECTURE_SN      NUMBER(20)    NOT NULL,
    SECONDS_WATCHED NUMBER(10)    DEFAULT 0 NOT NULL, 
    LAST_UPDATE     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    
    -- [제약조건 테이블 수준 정의]
    -- 1. 이 테이블의 PK는 사용자별 + 코스별 + 강의별 조합으로 고유해야 합니다.
    CONSTRAINT PK_LECTURE_PROGRESS PRIMARY KEY (USER_ID, COURSE_SN, LECTURE_SN), 
    
    -- 2. MEMBER 테이블 참조 외래키
    CONSTRAINT FK_LECTURE_PROGRESS_USER FOREIGN KEY (USER_ID) REFERENCES MEMBER (USER_ID),
    
    -- 3. LECTURE 테이블 참조 외래키 (부모의 복합키 컬럼 쌍을 그대로 똑같이 맞춰서 연결)
    CONSTRAINT FK_LECTURE_PROGRESS_LECTURE FOREIGN KEY (COURSE_SN, LECTURE_SN) REFERENCES LECTURE (COURSE_SN, LECTURE_SN)
);

-- COMMENT 설정 수정 및 추가
COMMENT ON TABLE LECTURE_PROGRESS IS '학생별 강의 수강 진행 상황을 관리하는 테이블';
COMMENT ON COLUMN LECTURE_PROGRESS.USER_ID IS '사용자 ID (학생)';
COMMENT ON COLUMN LECTURE_PROGRESS.COURSE_SN IS '강좌 고유 번호';
COMMENT ON COLUMN LECTURE_PROGRESS.LECTURE_SN IS '강의 고유 번호';
COMMENT ON COLUMN LECTURE_PROGRESS.SECONDS_WATCHED IS '마지막에 저장된 시청 시간(초)';
COMMENT ON COLUMN LECTURE_PROGRESS.LAST_UPDATE IS '마지막 업데이트 시간';
