CREATE TABLE SUNEUNG_GRADE_CUT (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    YEAR        NUMBER(4),
    EXAM_TYPE   VARCHAR2(10),   -- ExamType enum: 'CSAT', 'JUNE_MOCK', 'SEPT_MOCK'
    SUBJECT     VARCHAR2(50),
    GRADE       NUMBER(1),
    CUT_SCORE   NUMBER(5),
    PEOPLE      NUMBER(10),
    RATIO       NUMBER(5,2)
);