-- ============================================================
-- 업무 일지 테이블 (INSTRUCTOR_JOURNAL)
-- ============================================================
-- 목적: 강사가 작성하는 개인 업무 기록을 저장합니다.
--       업무 일지는 특정 클래스에 종속되지 않는 강사 개인 기록입니다.
--
-- 접근 제어 정책 (애플리케이션 레이어에서 강제):
--   - 강사 본인     : 본인 일지 전체 조회 / 작성 / 수정 / 삭제
--   - 수석 강사(T001): 전체 강사 일지 읽기 전용
--   - 원장(Z001)    : 전체 강사 일지 읽기 전용
--   - 그 외         : 접근 불가
-- ============================================================

create table instructor_journal (
    -- 일지 일련번호 (PK, 자동증가)
   jrnl_sn       number(20) generated by default as identity,

    -- 작성 강사 ID (FK → MEMBER.USER_ID)
   instr_user_id varchar2(20) not null,

    -- 일지 제목
   jrnl_title    varchar2(200) not null,

    -- 일지 본문 (자유 텍스트, 길이 제한 없음)
   jrnl_cont     clob not null,

    -- 업무 실시 날짜 (작성일과 다를 수 있음 — 사후 기록 지원)
   jrnl_dt       date not null,

    -- 등록일시 (자동 입력)
   reg_dt        timestamp default current_timestamp not null,

    -- 수정일시 (수정 시 애플리케이션에서 갱신)
   mdfcn_dt      timestamp null,
   constraint pk_instructor_journal primary key ( jrnl_sn ),
   constraint fk_jrnl_instr foreign key ( instr_user_id )
      references member ( user_id )
);

-- 강사별 날짜 내림차순 조회 최적화 인덱스
create index idx_jrnl_instr_dt on
   instructor_journal (
      instr_user_id,
      jrnl_dt
   desc );

-- 테이블·컬럼 코멘트
comment on table instructor_journal is
   '강사 업무 일지';
comment on column instructor_journal.jrnl_sn is
   'PK · 자동증가';
comment on column instructor_journal.instr_user_id is
   '작성 강사 ID (FK → MEMBER.USER_ID)';
comment on column instructor_journal.jrnl_title is
   '일지 제목';
comment on column instructor_journal.jrnl_cont is
   '일지 본문';
comment on column instructor_journal.jrnl_dt is
   '업무 실시 날짜';
comment on column instructor_journal.reg_dt is
   '등록일시';
comment on column instructor_journal.mdfcn_dt is
   '수정일시';