-- 직급별 메뉴 접근 권한 테이블
CREATE TABLE MENU_PERMISSION (
    MENU_CD     VARCHAR2(50)  NOT NULL,
    JOB_GRADE   VARCHAR2(10)  NOT NULL,
    ALLOWED     CHAR(1)       DEFAULT 'Y' NOT NULL,
    UPDATED_AT  DATE          DEFAULT SYSDATE,
    CONSTRAINT PK_MENU_PERMISSION PRIMARY KEY (MENU_CD, JOB_GRADE),
    CONSTRAINT CK_MENU_ALLOWED CHECK (ALLOWED IN ('Y', 'N'))
);

-- 초기 데이터 (UI 하드코딩 체크박스 상태 기준)
-- 컬럼 순서: MENU_CD, JOB_GRADE, ALLOWED
-- 직급: A001(행정팀장) A002(선임행정원) A003(행정원) A004(인턴) T001(수석강사) T002(전임강사) T003(조교)

-- ── 공통 업무 (전 직급 Y) ──
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('main_dashboard',    'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('messages',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messages',          'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('messenger',         'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('messenger',         'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('approval',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('approval',          'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('schedule',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('schedule',          'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('course_view',       'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('course_view',       'T003', 'Y', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'A004', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_issue', 'T003', 'Y', SYSDATE);

-- ── 원장 업무 (전 직급 N — 원장 D400은 별도 처리) ──
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('academic_monitoring','T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('system_log',        'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('system_log',        'T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('finance_analysis',  'T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('quality',           'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('quality',           'T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('perm_settings',     'T003', 'N', SYSDATE);

-- ── 행정팀장 업무 (A001만 Y) ──
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_monitor','T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('consultation',      'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('consultation',      'T003', 'N', SYSDATE);

INSERT INTO MENU_PERMISSION VALUES ('retention',         'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('retention',         'T003', 'N', SYSDATE);

-- ── 행정 업무 ──
-- 고객센터: A001 A002 A003 Y, 나머지 N
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('customer_center',   'T003', 'N', SYSDATE);

-- 사용자 관리: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('user_management',   'T003', 'N', SYSDATE);

-- 조직 관리: A001 A002 Y
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('org_management',    'T003', 'N', SYSDATE);

-- 블랙리스트: A001 A002 Y
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('blacklist',         'T003', 'N', SYSDATE);

-- 원비/수납: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('billing',           'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('billing',           'T003', 'N', SYSDATE);

-- 교재: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('textbook',          'T003', 'N', SYSDATE);

-- 주문: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('orders',            'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('orders',            'T003', 'N', SYSDATE);

-- 추천: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('featured',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('featured',          'T003', 'N', SYSDATE);

-- 쿠폰/포인트: A001 A002 Y
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('coupon',            'T003', 'N', SYSDATE);

-- 공통코드: A001 Y
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('common_codes',      'T003', 'N', SYSDATE);

-- 증명서 발급 관리: A001 A002 A003 Y
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','A003', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('certificate_manage','T003', 'N', SYSDATE);

-- 과목: A001 A002 Y
INSERT INTO MENU_PERMISSION VALUES ('subject',           'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'A002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'T001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'T002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('subject',           'T003', 'N', SYSDATE);

-- ── 강사 업무 ──
-- 담당 클래스: A001 T001 T002 T003 Y
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('classroom',         'T003', 'Y', SYSDATE);

-- 강사 게시판: A001 T001 T002 T003 Y
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('instructor_board',  'T003', 'Y', SYSDATE);

-- 문항 관리: T001 T002 Y (T003 N)
INSERT INTO MENU_PERMISSION VALUES ('questions',         'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('questions',         'T003', 'N', SYSDATE);

-- 업무 일지: A001 T001 T002 T003 Y
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('work_log',          'T003', 'Y', SYSDATE);

-- 커리큘럼: A001 T001 T002 Y (T003 N)
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'A001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('curriculum',        'T003', 'N', SYSDATE);

-- 개인 페이지: T001 T002 T003 Y
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'A001', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'A002', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'A003', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'A004', 'N', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'T001', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'T002', 'Y', SYSDATE);
INSERT INTO MENU_PERMISSION VALUES ('my_page',           'T003', 'Y', SYSDATE);

COMMIT;
