-- =====================================================================
-- 원비 청구(TUITION_BILL) 테이블 · 학생별 월 청구 원장
-- 가입일(MEMBER.JOIN_DT) 기준 매월 결제일 청구를 선(先)생성하고
-- 상태(미납→연체→완료)만 전이시킨다. 행 이동 없음.
--   · 미납자 관리   = BILL_STAT_CD IN (미납, 연체)
--   · 미납 회차     = 학생별 미납/연체 건수 COUNT (블랙리스트 기준)
--   · 결제 완료     = BILL_STAT_CD = 완료, PAY_SN 으로 수납내역 연결
-- ※ create_tuition_payment_table.sql 실행 후 실행 (PAY_SN FK 의존)
-- ※ select box 값(항목·상태)은 모두 공통코드(COM_CD) 사용
-- =====================================================================

CREATE TABLE TUITION_BILL (
    BILL_SN       NUMBER(20)     GENERATED BY DEFAULT AS IDENTITY,
    USER_ID       VARCHAR2(20)   NOT NULL,
    BILL_YM       CHAR(6)        NOT NULL,
    BILL_ITEM_CD  CHAR(10)       NOT NULL,
    BILL_AMT      NUMBER(15)     NOT NULL,
    DUE_DT        DATE           NOT NULL,
    BILL_STAT_CD  CHAR(10)       DEFAULT '01' NOT NULL,
    PAY_SN        NUMBER(20)     NULL,
    REG_DT        TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MDFCN_DT      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT PK_TUITION_BILL PRIMARY KEY (BILL_SN),
    CONSTRAINT UK_TUITION_BILL_USER_YM UNIQUE (USER_ID, BILL_YM),
    CONSTRAINT FK_TUITION_BILL_MEMBER  FOREIGN KEY (USER_ID) REFERENCES MEMBER (USER_ID),
    CONSTRAINT FK_TUITION_BILL_PAYMENT FOREIGN KEY (PAY_SN)  REFERENCES TUITION_PAYMENT (PAY_SN)
);

COMMENT ON TABLE  TUITION_BILL              IS '원비 청구 원장 · 학생 1명 / 청구월 1건';
COMMENT ON COLUMN TUITION_BILL.BILL_SN      IS '기본키(PK) · 시퀀스';
COMMENT ON COLUMN TUITION_BILL.USER_ID      IS 'MEMBER.USER_ID 참조(FK) · 청구 대상 학생(ROLE_STUDENT)';
COMMENT ON COLUMN TUITION_BILL.BILL_YM      IS '청구년월 YYYYMM · (USER_ID, BILL_YM) 중복 청구 방지';
COMMENT ON COLUMN TUITION_BILL.BILL_ITEM_CD IS '항목 · 공통코드 CL_CODE=222(원비 항목)';
COMMENT ON COLUMN TUITION_BILL.BILL_AMT     IS '청구 금액';
COMMENT ON COLUMN TUITION_BILL.DUE_DT       IS '결제일 · 가입일(JOIN_DT)의 일(day) 기준, 말일 보정';
COMMENT ON COLUMN TUITION_BILL.BILL_STAT_CD IS '청구 상태 · 공통코드 CL_CODE=224(01:미납/02:연체/03:완료)';
COMMENT ON COLUMN TUITION_BILL.PAY_SN       IS 'TUITION_PAYMENT.PAY_SN 참조(FK) · 완료 시 수납내역 연결';
COMMENT ON COLUMN TUITION_BILL.REG_DT       IS '등록일시(청구 생성 시각)';
COMMENT ON COLUMN TUITION_BILL.MDFCN_DT     IS '수정일시(상태 전이 시각)';

-- 미납자 조회(상태별), 학생별 미납 회차 집계 최적화
CREATE INDEX IDX_TUITION_BILL_STAT ON TUITION_BILL (BILL_STAT_CD);
CREATE INDEX IDX_TUITION_BILL_USER ON TUITION_BILL (USER_ID);
