-- 강사 약력/저서/수상/방송출연 관리 테이블
-- CAREER_TYPE_CD: 01 약력 / 02 저서 / 03 수상 / 04 방송출연
-- CAREER_END_YR: NULL이면 현재 진행 중
CREATE TABLE INSTRUCTOR_CAREER (
    CAREER_SN       NUMBER          NOT NULL,
    INSTR_USER_ID   VARCHAR2(20)    NOT NULL,
    CAREER_TYPE_CD  CHAR(2)         NOT NULL,
    CAREER_STRT_YR  CHAR(4),
    CAREER_END_YR   CHAR(4),
    CAREER_CONT     VARCHAR2(500)   NOT NULL,
    SORT_ORD        NUMBER          DEFAULT 0,
    CONSTRAINT PK_INSTRUCTOR_CAREER PRIMARY KEY (CAREER_SN),
    CONSTRAINT FK_CAREER_INSTRUCTOR FOREIGN KEY (INSTR_USER_ID)
        REFERENCES INSTRUCTOR (INSTR_USER_ID)
);

CREATE SEQUENCE SEQ_INSTRUCTOR_CAREER START WITH 1 INCREMENT BY 1 NOCACHE;
