-- =====================================================================
-- 원비 수납내역(TUITION_PAYMENT) 테이블
-- 오프라인 카드결제 → 외부 경리 프로그램(외부 경리 프로그램) → Excel 업로드로 적재
-- ※ 온라인 강의/교재 결제(ORDERS·PAY_HIST)와 목적이 다른 별도 테이블
-- ※ select box 값(항목·결제수단·상태)은 모두 공통코드(COM_CD) 사용
-- =====================================================================

CREATE TABLE TUITION_PAYMENT (
    PAY_SN          NUMBER(20)     GENERATED BY DEFAULT AS IDENTITY,
    USER_ID         VARCHAR2(20)   NOT NULL,
    EXT_PAY_ID      VARCHAR2(100)  NOT NULL,
    PAY_ITEM_CD     CHAR(10)       NOT NULL,
    PAY_AMT         NUMBER(15)     NOT NULL,
    PAY_MTHD_CD     CHAR(10)       NOT NULL,
    CARD_NM         VARCHAR2(50)   NULL,
    INSTALLMENT_MM  NUMBER(3)      DEFAULT 0 NOT NULL,
    PAY_STAT_CD     CHAR(10)       DEFAULT '01' NOT NULL,
    PAY_DT          TIMESTAMP      NOT NULL,
    REG_DT          TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TUITION_PAYMENT PRIMARY KEY (PAY_SN),
    CONSTRAINT UK_TUITION_PAYMENT_EXT_ID UNIQUE (EXT_PAY_ID),
    CONSTRAINT FK_TUITION_PAYMENT_MEMBER FOREIGN KEY (USER_ID) REFERENCES MEMBER (USER_ID)
);

COMMENT ON TABLE  TUITION_PAYMENT                IS '원비 수납내역 · 외부 경리 프로그램 Excel 업로드로 적재되는 실제 결제 완료 데이터';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_SN         IS '기본키(PK) · 시퀀스';
COMMENT ON COLUMN TUITION_PAYMENT.USER_ID        IS 'MEMBER.USER_ID 참조(FK) · 결제 학생';
COMMENT ON COLUMN TUITION_PAYMENT.EXT_PAY_ID     IS '외부 경리 프로그램 결제ID · 중복 업로드 방지(UNIQUE) · 외부 경리 서비스 조회 키';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_ITEM_CD    IS '항목 · 공통코드 CL_CODE=222(원비 항목)';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_AMT        IS '결제 금액';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_MTHD_CD    IS '결제수단 · 공통코드 CL_CODE=223(01:카드/02:카카오페이/03:토스페이)';
COMMENT ON COLUMN TUITION_PAYMENT.CARD_NM        IS '카드사명 예: OO카드 (결제수단=카드일 때만)';
COMMENT ON COLUMN TUITION_PAYMENT.INSTALLMENT_MM IS '할부개월 (0=일시불)';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_STAT_CD    IS '결제 상태 · 공통코드 CL_CODE=225(01:완료/02:미완료)';
COMMENT ON COLUMN TUITION_PAYMENT.PAY_DT         IS '수납일시';
COMMENT ON COLUMN TUITION_PAYMENT.REG_DT         IS '등록일시(업로드 시각)';

-- 학생별/일자별 수납 조회 최적화
CREATE INDEX IDX_TUITION_PAYMENT_USER ON TUITION_PAYMENT (USER_ID);
CREATE INDEX IDX_TUITION_PAYMENT_DT   ON TUITION_PAYMENT (PAY_DT);
