-- 강사 상세 페이지 대표 강좌 테이블 (최대 4개 노출)
-- DISPLAY_ORDER: 1~4, 오름차순 정렬 기준
CREATE TABLE INSTRUCTOR_FEATURED_COURSE (
    INSTR_UUID      VARCHAR2(36)    NOT NULL,
    COURSE_SN       NUMBER          NOT NULL,
    DISPLAY_ORDER   NUMBER(1)       NOT NULL,
    CONSTRAINT PK_INSTR_FEATURED_COURSE PRIMARY KEY (INSTR_UUID, COURSE_SN),
    CONSTRAINT UQ_INSTR_FEATURED_ORDER  UNIQUE (INSTR_UUID, DISPLAY_ORDER),
    CONSTRAINT FK_FEAT_INSTRUCTOR FOREIGN KEY (INSTR_UUID)
        REFERENCES INSTRUCTOR (INSTR_UUID),
    CONSTRAINT FK_FEAT_COURSE FOREIGN KEY (COURSE_SN)
        REFERENCES COURSE (COURSE_SN),
    CONSTRAINT CK_FEAT_DISPLAY_ORDER CHECK (DISPLAY_ORDER BETWEEN 1 AND 4)
);
