package kr.or.ddit.finalProject.dto.exam;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * EXAM 테이블 매핑 DTO
 *
 * [EXAM_STAT_CD 코드 정의]
 *   01 - 정상 (기본값)
 *   99 - 삭제됨 (EXAM 테이블에 DEL_YN 컬럼 없음 → EXAM_STAT_CD로 논리 삭제)
 *
 * [날짜 형식]
 *   examStrtDt / examEndDt: 'YYYY-MM-DD HH24:MI' 포맷 문자열
 *   HTML datetime-local 입력값(YYYY-MM-DDTHH:mm)과 형식이 다르므로
 *   수정 폼에서 표시할 때 주의가 필요합니다.
 */
@Data
@NoArgsConstructor
public class ExamDto {

    /** 시험 일련번호 (PK, GENERATED BY DEFAULT AS IDENTITY) */
    private Long examSn;

    /** 시험 유형 코드 (COM_CD 공통코드 참조, 선택 입력) */
    private String examTypeCd;

    /** 담당 강사 ID (= instrUserId, 본인 시험 식별 기준) */
    private String examChrgUserId;

    /** 시험명 */
    private String examRegNm;

    /** 등록 일시 (TO_CHAR 포맷 문자열) */
    private String examRegDt;

    /** 시험 시작 일시 (TO_CHAR 포맷 문자열) */
    private String examStrtDt;

    /** 시험 종료 일시 (TO_CHAR 포맷 문자열) */
    private String examEndDt;

    /**
     * 상태 코드
     * 01: 정상 / 99: 삭제됨
     */
    private String examStatCd;

    // ── 연관 데이터 (DB 컬럼 아님) ─────────────────────────────────────────

    /**
     * 배정된 문항 수 (EXAM_QUESTION COUNT 서브쿼리, selectMyExams에서만 채워짐)
     * 목록 테이블의 "문항 수" 컬럼 표시에 사용합니다.
     */
    private Integer qstnCnt;

    /** 연결된 강좌(클래스) 일련번호 (CLASSROOM.CLASS_SN, nullable) */
    private Long classSn;

    /** 강좌명 (JOIN 조회 시 채워짐, DB 컬럼 아님) */
    private String classNm;

    /**
     * 이 시험에 배정된 문항 목록
     * EXAM_QUESTION + QUESTION_LIST 조인 결과이며,
     * retrieveMyExams 조회 시 서비스에서 별도로 채워집니다.
     * null 방지를 위해 빈 리스트로 초기화합니다.
     */
    private List<ExamQuestionDto> questions = new ArrayList<>();
}
