package kr.or.ddit.finalProject.dto.exam;

import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

/**
 * QUESTION_LIST 테이블 매핑 DTO
 *
 * [QSTN_TYPE_CD 코드 정의]
 *   01 - 객관식 (choices 필드에 보기 4개 포함)
 *   02 - 주관식 (단답형, choices = null)
 *   03 - 서술형 (choices = null)
 *
 * [QSTN_CN 저장 형식]
 *   DB에 JSON 문자열로 저장합니다.
 *   객관식: {"stem":"...","choices":["보기1","보기2","보기3","보기4"]}
 *   주관식: {"stem":"...","maxLength":50}          ← 답안 최대 글자 수 (선택)
 *   서술형: {"stem":"...","scoringCriteria":"..."}  ← 채점 기준 (선택)
 *   조회 후 서비스에서 필드로 파싱합니다.
 *
 * [STAT_CD 코드 정의]
 *   01 - 정상 (기본값)
 *   99 - 삭제됨 (DEL_YN 컬럼 없음 → STAT_CD로 논리 삭제 처리)
 */
@Data
public class QuestionDto {

    /** 문항 일련번호 (PK, GENERATED BY DEFAULT AS IDENTITY) */
    private Long qstnSn;

    /** 과목 소분류 코드 (COM_CD 참조, 선택 입력) */
    private String subjDtclCd;

    /** 등록자 ID (= 문항을 생성한 강사 instrUserId) */
    private String rgtrId;

    /** 최종 수정자 ID */
    private String lastMdfrId;

    /** 등록 일시 */
    private String regDt;

    /**
     * 문항 유형 코드
     * 01: 객관식 / 02: 주관식 / 03: 서술형
     */
    private String qstnTypeCd;

    /** 배점 (소수점 2자리, 예: 5.00) */
    private BigDecimal allocScr;

    /**
     * 정답
     * 객관식: "1"~"4" 중 하나
     * 주관식/서술형: 정답 텍스트 (채점 참고용)
     */
    private String corrAnswCn;

    /** 해설 (선택 입력) */
    private String explnCn;

    /**
     * 상태 코드
     * 01: 정상 / 99: 삭제됨
     * QUESTION_LIST에 DEL_YN 컬럼이 없으므로 STAT_CD로 논리 삭제를 처리합니다.
     */
    private String statCd;

    /**
     * 문항 본문 + 보기를 JSON으로 직렬화한 문자열 (DB 컬럼 QSTN_CN, CLOB)
     * 예: {"stem":"문제내용","choices":["보기1","보기2","보기3","보기4"]}
     * 조회 시 서비스에서 stem/choices 필드로 파싱됩니다.
     * 저장 시 서비스에서 stem/choices를 조합해 이 필드를 채웁니다.
     */
    private String qstnCn;

    // ── QSTN_CN JSON 파싱 결과 (DB 컬럼 아님, 서비스에서 채워짐) ──────────

    /**
     * 문항 본문 (QSTN_CN JSON의 "stem" 값에서 파싱, DB 컬럼 아님)
     */
    private String stem;

    /**
     * 객관식 보기 목록 (QSTN_CN JSON의 "choices" 배열, DB 컬럼 아님)
     * 객관식(01)에만 해당하며, 나머지 유형은 null 입니다.
     */
    private List<String> choices;

    /**
     * 주관식(02) 전용 — 답안 최대 글자 수 (QSTN_CN JSON의 "maxLength", DB 컬럼 아님)
     * null 허용. 설정하지 않으면 글자 수 제한 없음.
     */
    private Integer maxLength;

    /**
     * 서술형(03) 전용 — 채점 기준 (QSTN_CN JSON의 "scoringCriteria", DB 컬럼 아님)
     * 채점자가 참고할 루브릭/기준을 자유 서술합니다.
     */
    private String scoringCriteria;
}
